// Periodic table — full 118 elements with name, symbol, atomic number, atomic mass, group/period for grid placement, and category.
export interface Element {
  z: number;
  symbol: string;
  name: string;
  mass: number;
  group: number; // 1..18 (lanthanides/actinides use group 3 with row offset)
  period: number; // 1..7 (lanthanides=8, actinides=9 visually)
  category: ElementCategory;
}

export type ElementCategory =
  | "alkali"
  | "alkaline-earth"
  | "transition"
  | "post-transition"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble"
  | "lanthanide"
  | "actinide"
  | "unknown";

export const CATEGORY_COLOR: Record<ElementCategory, string> = {
  alkali: "bg-rose-200 dark:bg-rose-900/60 text-rose-900 dark:text-rose-100 border-rose-400/60",
  "alkaline-earth":
    "bg-orange-200 dark:bg-orange-900/60 text-orange-900 dark:text-orange-100 border-orange-400/60",
  transition:
    "bg-amber-100 dark:bg-amber-900/50 text-amber-900 dark:text-amber-100 border-amber-400/60",
  "post-transition":
    "bg-slate-200 dark:bg-slate-700/60 text-slate-900 dark:text-slate-100 border-slate-400/60",
  metalloid: "bg-teal-200 dark:bg-teal-900/60 text-teal-900 dark:text-teal-100 border-teal-400/60",
  nonmetal: "bg-lime-200 dark:bg-lime-900/60 text-lime-900 dark:text-lime-100 border-lime-400/60",
  halogen: "bg-cyan-200 dark:bg-cyan-900/60 text-cyan-900 dark:text-cyan-100 border-cyan-400/60",
  noble:
    "bg-violet-200 dark:bg-violet-900/60 text-violet-900 dark:text-violet-100 border-violet-400/60",
  lanthanide: "bg-pink-200 dark:bg-pink-900/60 text-pink-900 dark:text-pink-100 border-pink-400/60",
  actinide:
    "bg-fuchsia-200 dark:bg-fuchsia-900/60 text-fuchsia-900 dark:text-fuchsia-100 border-fuchsia-400/60",
  unknown: "bg-muted text-muted-foreground border-border/60",
};

export const ELEMENTS: Element[] = [
  { z: 1, symbol: "H", name: "Hydrogen", mass: 1.008, group: 1, period: 1, category: "nonmetal" },
  { z: 2, symbol: "He", name: "Helium", mass: 4.0026, group: 18, period: 1, category: "noble" },
  { z: 3, symbol: "Li", name: "Lithium", mass: 6.94, group: 1, period: 2, category: "alkali" },
  {
    z: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: 9.0122,
    group: 2,
    period: 2,
    category: "alkaline-earth",
  },
  { z: 5, symbol: "B", name: "Boron", mass: 10.81, group: 13, period: 2, category: "metalloid" },
  { z: 6, symbol: "C", name: "Carbon", mass: 12.011, group: 14, period: 2, category: "nonmetal" },
  { z: 7, symbol: "N", name: "Nitrogen", mass: 14.007, group: 15, period: 2, category: "nonmetal" },
  { z: 8, symbol: "O", name: "Oxygen", mass: 15.999, group: 16, period: 2, category: "nonmetal" },
  { z: 9, symbol: "F", name: "Fluorine", mass: 18.998, group: 17, period: 2, category: "halogen" },
  { z: 10, symbol: "Ne", name: "Neon", mass: 20.18, group: 18, period: 2, category: "noble" },
  { z: 11, symbol: "Na", name: "Sodium", mass: 22.99, group: 1, period: 3, category: "alkali" },
  {
    z: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.305,
    group: 2,
    period: 3,
    category: "alkaline-earth",
  },
  {
    z: 13,
    symbol: "Al",
    name: "Aluminium",
    mass: 26.982,
    group: 13,
    period: 3,
    category: "post-transition",
  },
  {
    z: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28.085,
    group: 14,
    period: 3,
    category: "metalloid",
  },
  {
    z: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.974,
    group: 15,
    period: 3,
    category: "nonmetal",
  },
  { z: 16, symbol: "S", name: "Sulfur", mass: 32.06, group: 16, period: 3, category: "nonmetal" },
  { z: 17, symbol: "Cl", name: "Chlorine", mass: 35.45, group: 17, period: 3, category: "halogen" },
  { z: 18, symbol: "Ar", name: "Argon", mass: 39.948, group: 18, period: 3, category: "noble" },
  { z: 19, symbol: "K", name: "Potassium", mass: 39.098, group: 1, period: 4, category: "alkali" },
  {
    z: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.078,
    group: 2,
    period: 4,
    category: "alkaline-earth",
  },
  {
    z: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.956,
    group: 3,
    period: 4,
    category: "transition",
  },
  {
    z: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.867,
    group: 4,
    period: 4,
    category: "transition",
  },
  {
    z: 23,
    symbol: "V",
    name: "Vanadium",
    mass: 50.942,
    group: 5,
    period: 4,
    category: "transition",
  },
  {
    z: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: 51.996,
    group: 6,
    period: 4,
    category: "transition",
  },
  {
    z: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: 54.938,
    group: 7,
    period: 4,
    category: "transition",
  },
  { z: 26, symbol: "Fe", name: "Iron", mass: 55.845, group: 8, period: 4, category: "transition" },
  {
    z: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: 58.933,
    group: 9,
    period: 4,
    category: "transition",
  },
  {
    z: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: 58.693,
    group: 10,
    period: 4,
    category: "transition",
  },
  {
    z: 29,
    symbol: "Cu",
    name: "Copper",
    mass: 63.546,
    group: 11,
    period: 4,
    category: "transition",
  },
  { z: 30, symbol: "Zn", name: "Zinc", mass: 65.38, group: 12, period: 4, category: "transition" },
  {
    z: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: 69.723,
    group: 13,
    period: 4,
    category: "post-transition",
  },
  {
    z: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: 72.63,
    group: 14,
    period: 4,
    category: "metalloid",
  },
  {
    z: 33,
    symbol: "As",
    name: "Arsenic",
    mass: 74.922,
    group: 15,
    period: 4,
    category: "metalloid",
  },
  {
    z: 34,
    symbol: "Se",
    name: "Selenium",
    mass: 78.971,
    group: 16,
    period: 4,
    category: "nonmetal",
  },
  { z: 35, symbol: "Br", name: "Bromine", mass: 79.904, group: 17, period: 4, category: "halogen" },
  { z: 36, symbol: "Kr", name: "Krypton", mass: 83.798, group: 18, period: 4, category: "noble" },
  { z: 37, symbol: "Rb", name: "Rubidium", mass: 85.468, group: 1, period: 5, category: "alkali" },
  {
    z: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: 87.62,
    group: 2,
    period: 5,
    category: "alkaline-earth",
  },
  {
    z: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: 88.906,
    group: 3,
    period: 5,
    category: "transition",
  },
  {
    z: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: 91.224,
    group: 4,
    period: 5,
    category: "transition",
  },
  {
    z: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: 92.906,
    group: 5,
    period: 5,
    category: "transition",
  },
  {
    z: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: 95.95,
    group: 6,
    period: 5,
    category: "transition",
  },
  {
    z: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: 98,
    group: 7,
    period: 5,
    category: "transition",
  },
  {
    z: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: 101.07,
    group: 8,
    period: 5,
    category: "transition",
  },
  {
    z: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: 102.91,
    group: 9,
    period: 5,
    category: "transition",
  },
  {
    z: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: 106.42,
    group: 10,
    period: 5,
    category: "transition",
  },
  {
    z: 47,
    symbol: "Ag",
    name: "Silver",
    mass: 107.87,
    group: 11,
    period: 5,
    category: "transition",
  },
  {
    z: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: 112.41,
    group: 12,
    period: 5,
    category: "transition",
  },
  {
    z: 49,
    symbol: "In",
    name: "Indium",
    mass: 114.82,
    group: 13,
    period: 5,
    category: "post-transition",
  },
  {
    z: 50,
    symbol: "Sn",
    name: "Tin",
    mass: 118.71,
    group: 14,
    period: 5,
    category: "post-transition",
  },
  {
    z: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: 121.76,
    group: 15,
    period: 5,
    category: "metalloid",
  },
  {
    z: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: 127.6,
    group: 16,
    period: 5,
    category: "metalloid",
  },
  { z: 53, symbol: "I", name: "Iodine", mass: 126.9, group: 17, period: 5, category: "halogen" },
  { z: 54, symbol: "Xe", name: "Xenon", mass: 131.29, group: 18, period: 5, category: "noble" },
  { z: 55, symbol: "Cs", name: "Caesium", mass: 132.91, group: 1, period: 6, category: "alkali" },
  {
    z: 56,
    symbol: "Ba",
    name: "Barium",
    mass: 137.33,
    group: 2,
    period: 6,
    category: "alkaline-earth",
  },
  {
    z: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.91,
    group: 3,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: 140.12,
    group: 4,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: 140.91,
    group: 5,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: 144.24,
    group: 6,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: 145,
    group: 7,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: 150.36,
    group: 8,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 63,
    symbol: "Eu",
    name: "Europium",
    mass: 151.96,
    group: 9,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: 157.25,
    group: 10,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: 158.93,
    group: 11,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: 162.5,
    group: 12,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: 164.93,
    group: 13,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 68,
    symbol: "Er",
    name: "Erbium",
    mass: 167.26,
    group: 14,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: 168.93,
    group: 15,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: 173.05,
    group: 16,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: 174.97,
    group: 17,
    period: 8,
    category: "lanthanide",
  },
  {
    z: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: 178.49,
    group: 4,
    period: 6,
    category: "transition",
  },
  {
    z: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: 180.95,
    group: 5,
    period: 6,
    category: "transition",
  },
  {
    z: 74,
    symbol: "W",
    name: "Tungsten",
    mass: 183.84,
    group: 6,
    period: 6,
    category: "transition",
  },
  {
    z: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: 186.21,
    group: 7,
    period: 6,
    category: "transition",
  },
  {
    z: 76,
    symbol: "Os",
    name: "Osmium",
    mass: 190.23,
    group: 8,
    period: 6,
    category: "transition",
  },
  {
    z: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: 192.22,
    group: 9,
    period: 6,
    category: "transition",
  },
  {
    z: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: 195.08,
    group: 10,
    period: 6,
    category: "transition",
  },
  { z: 79, symbol: "Au", name: "Gold", mass: 196.97, group: 11, period: 6, category: "transition" },
  {
    z: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: 200.59,
    group: 12,
    period: 6,
    category: "transition",
  },
  {
    z: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: 204.38,
    group: 13,
    period: 6,
    category: "post-transition",
  },
  {
    z: 82,
    symbol: "Pb",
    name: "Lead",
    mass: 207.2,
    group: 14,
    period: 6,
    category: "post-transition",
  },
  {
    z: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: 208.98,
    group: 15,
    period: 6,
    category: "post-transition",
  },
  {
    z: 84,
    symbol: "Po",
    name: "Polonium",
    mass: 209,
    group: 16,
    period: 6,
    category: "post-transition",
  },
  { z: 85, symbol: "At", name: "Astatine", mass: 210, group: 17, period: 6, category: "halogen" },
  { z: 86, symbol: "Rn", name: "Radon", mass: 222, group: 18, period: 6, category: "noble" },
  { z: 87, symbol: "Fr", name: "Francium", mass: 223, group: 1, period: 7, category: "alkali" },
  {
    z: 88,
    symbol: "Ra",
    name: "Radium",
    mass: 226,
    group: 2,
    period: 7,
    category: "alkaline-earth",
  },
  { z: 89, symbol: "Ac", name: "Actinium", mass: 227, group: 3, period: 9, category: "actinide" },
  { z: 90, symbol: "Th", name: "Thorium", mass: 232.04, group: 4, period: 9, category: "actinide" },
  {
    z: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: 231.04,
    group: 5,
    period: 9,
    category: "actinide",
  },
  { z: 92, symbol: "U", name: "Uranium", mass: 238.03, group: 6, period: 9, category: "actinide" },
  { z: 93, symbol: "Np", name: "Neptunium", mass: 237, group: 7, period: 9, category: "actinide" },
  { z: 94, symbol: "Pu", name: "Plutonium", mass: 244, group: 8, period: 9, category: "actinide" },
  { z: 95, symbol: "Am", name: "Americium", mass: 243, group: 9, period: 9, category: "actinide" },
  { z: 96, symbol: "Cm", name: "Curium", mass: 247, group: 10, period: 9, category: "actinide" },
  { z: 97, symbol: "Bk", name: "Berkelium", mass: 247, group: 11, period: 9, category: "actinide" },
  {
    z: 98,
    symbol: "Cf",
    name: "Californium",
    mass: 251,
    group: 12,
    period: 9,
    category: "actinide",
  },
  {
    z: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: 252,
    group: 13,
    period: 9,
    category: "actinide",
  },
  { z: 100, symbol: "Fm", name: "Fermium", mass: 257, group: 14, period: 9, category: "actinide" },
  {
    z: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: 258,
    group: 15,
    period: 9,
    category: "actinide",
  },
  { z: 102, symbol: "No", name: "Nobelium", mass: 259, group: 16, period: 9, category: "actinide" },
  {
    z: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: 266,
    group: 17,
    period: 9,
    category: "actinide",
  },
  {
    z: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: 267,
    group: 4,
    period: 7,
    category: "transition",
  },
  { z: 105, symbol: "Db", name: "Dubnium", mass: 268, group: 5, period: 7, category: "transition" },
  {
    z: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: 269,
    group: 6,
    period: 7,
    category: "transition",
  },
  { z: 107, symbol: "Bh", name: "Bohrium", mass: 270, group: 7, period: 7, category: "transition" },
  { z: 108, symbol: "Hs", name: "Hassium", mass: 277, group: 8, period: 7, category: "transition" },
  { z: 109, symbol: "Mt", name: "Meitnerium", mass: 278, group: 9, period: 7, category: "unknown" },
  {
    z: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: 281,
    group: 10,
    period: 7,
    category: "unknown",
  },
  {
    z: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: 282,
    group: 11,
    period: 7,
    category: "unknown",
  },
  {
    z: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: 285,
    group: 12,
    period: 7,
    category: "post-transition",
  },
  { z: 113, symbol: "Nh", name: "Nihonium", mass: 286, group: 13, period: 7, category: "unknown" },
  { z: 114, symbol: "Fl", name: "Flerovium", mass: 289, group: 14, period: 7, category: "unknown" },
  { z: 115, symbol: "Mc", name: "Moscovium", mass: 290, group: 15, period: 7, category: "unknown" },
  {
    z: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: 293,
    group: 16,
    period: 7,
    category: "unknown",
  },
  {
    z: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: 294,
    group: 17,
    period: 7,
    category: "unknown",
  },
  { z: 118, symbol: "Og", name: "Oganesson", mass: 294, group: 18, period: 7, category: "noble" },
];
