/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SmartSolvePhysRouteImport } from './routes/smart-solve-phys'
import { Route as SmartSolvePapersRouteImport } from './routes/smart-solve-papers'
import { Route as SmartSolveChemRouteImport } from './routes/smart-solve-chem'
import { Route as SmartSolveBioRouteImport } from './routes/smart-solve-bio'
import { Route as SmartSolveAllRouteImport } from './routes/smart-solve-all'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SmartSolvePhysExamPreviewRouteImport } from './routes/smart-solve-phys_.exam-preview'
import { Route as SmartSolvePapersPaperIdRouteImport } from './routes/smart-solve-papers_.$paperId'
import { Route as SmartSolveChemExamPreviewRouteImport } from './routes/smart-solve-chem_.exam-preview'
import { Route as SmartSolveBioExamPreviewRouteImport } from './routes/smart-solve-bio_.exam-preview'
import { Route as SmartSolveAllExamPreviewRouteImport } from './routes/smart-solve-all_.exam-preview'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as DashboardDeskRouteImport } from './routes/dashboard.desk'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as ApiWalletRouteImport } from './routes/api/wallet'
import { Route as ApiVolunteerApplicationsRouteImport } from './routes/api/volunteer-applications'
import { Route as ApiStreaksRouteImport } from './routes/api/streaks'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPlannerTasksRouteImport } from './routes/api/planner-tasks'
import { Route as ApiPapersOverridesRouteImport } from './routes/api/papers-overrides'
import { Route as ApiPapersRouteImport } from './routes/api/papers'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiFeedbackNotesRouteImport } from './routes/api/feedback-notes'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiExamPreviewSharesRouteImport } from './routes/api/exam-preview-shares'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiDailyGoalsRouteImport } from './routes/api/daily-goals'
import { Route as ApiDailyChallengeRouteImport } from './routes/api/daily-challenge'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as DashboardTablesSubjectRouteImport } from './routes/dashboard.tables.$subject'
import { Route as ApiPublicProfileUsernameRouteImport } from './routes/api/public-profile.$username'
import { Route as ApiPlannerTasksIdRouteImport } from './routes/api/planner-tasks.$id'
import { Route as ApiPapersPaperIdRouteImport } from './routes/api/papers.$paperId'
import { Route as ApiFeedbackNotesIdRouteImport } from './routes/api/feedback-notes.$id'
import { Route as ApiExamPreviewSharesShareIdRouteImport } from './routes/api/exam-preview-shares.$shareId'
import { Route as ApiAdminSeedRouteImport } from './routes/api/admin.seed'
import { Route as ApiAdminInitRouteImport } from './routes/api/admin.init'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin.bootstrap'
import { Route as ApiAccountResolveRouteImport } from './routes/api/account.resolve'
import { Route as AdminEditorPaperIdRouteImport } from './routes/admin.editor.$paperId'
import { Route as ApiPapersPaperIdThresholdsRouteImport } from './routes/api/papers.$paperId.thresholds'
import { Route as ApiPapersPaperIdQuestionsRouteImport } from './routes/api/papers.$paperId.questions'
import { Route as ApiPapersPaperIdAnswerKeyRouteImport } from './routes/api/papers.$paperId.answer-key'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolvePhysRoute = SmartSolvePhysRouteImport.update({
  id: '/smart-solve-phys',
  path: '/smart-solve-phys',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolvePapersRoute = SmartSolvePapersRouteImport.update({
  id: '/smart-solve-papers',
  path: '/smart-solve-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolveChemRoute = SmartSolveChemRouteImport.update({
  id: '/smart-solve-chem',
  path: '/smart-solve-chem',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolveBioRoute = SmartSolveBioRouteImport.update({
  id: '/smart-solve-bio',
  path: '/smart-solve-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolveAllRoute = SmartSolveAllRouteImport.update({
  id: '/smart-solve-all',
  path: '/smart-solve-all',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SmartSolvePhysExamPreviewRoute =
  SmartSolvePhysExamPreviewRouteImport.update({
    id: '/smart-solve-phys_/exam-preview',
    path: '/smart-solve-phys/exam-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const SmartSolvePapersPaperIdRoute = SmartSolvePapersPaperIdRouteImport.update({
  id: '/smart-solve-papers_/$paperId',
  path: '/smart-solve-papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSolveChemExamPreviewRoute =
  SmartSolveChemExamPreviewRouteImport.update({
    id: '/smart-solve-chem_/exam-preview',
    path: '/smart-solve-chem/exam-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const SmartSolveBioExamPreviewRoute =
  SmartSolveBioExamPreviewRouteImport.update({
    id: '/smart-solve-bio_/exam-preview',
    path: '/smart-solve-bio/exam-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const SmartSolveAllExamPreviewRoute =
  SmartSolveAllExamPreviewRouteImport.update({
    id: '/smart-solve-all_/exam-preview',
    path: '/smart-solve-all/exam-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRoute,
} as any)
const DashboardDeskRoute = DashboardDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWalletRoute = ApiWalletRouteImport.update({
  id: '/api/wallet',
  path: '/api/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVolunteerApplicationsRoute =
  ApiVolunteerApplicationsRouteImport.update({
    id: '/api/volunteer-applications',
    path: '/api/volunteer-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStreaksRoute = ApiStreaksRouteImport.update({
  id: '/api/streaks',
  path: '/api/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlannerTasksRoute = ApiPlannerTasksRouteImport.update({
  id: '/api/planner-tasks',
  path: '/api/planner-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPapersOverridesRoute = ApiPapersOverridesRouteImport.update({
  id: '/api/papers-overrides',
  path: '/api/papers-overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPapersRoute = ApiPapersRouteImport.update({
  id: '/api/papers',
  path: '/api/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackNotesRoute = ApiFeedbackNotesRouteImport.update({
  id: '/api/feedback-notes',
  path: '/api/feedback-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamPreviewSharesRoute = ApiExamPreviewSharesRouteImport.update({
  id: '/api/exam-preview-shares',
  path: '/api/exam-preview-shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyGoalsRoute = ApiDailyGoalsRouteImport.update({
  id: '/api/daily-goals',
  path: '/api/daily-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyChallengeRoute = ApiDailyChallengeRouteImport.update({
  id: '/api/daily-challenge',
  path: '/api/daily-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTablesSubjectRoute = DashboardTablesSubjectRouteImport.update({
  id: '/tables/$subject',
  path: '/tables/$subject',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicProfileUsernameRoute =
  ApiPublicProfileUsernameRouteImport.update({
    id: '/api/public-profile/$username',
    path: '/api/public-profile/$username',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlannerTasksIdRoute = ApiPlannerTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPlannerTasksRoute,
} as any)
const ApiPapersPaperIdRoute = ApiPapersPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => ApiPapersRoute,
} as any)
const ApiFeedbackNotesIdRoute = ApiFeedbackNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFeedbackNotesRoute,
} as any)
const ApiExamPreviewSharesShareIdRoute =
  ApiExamPreviewSharesShareIdRouteImport.update({
    id: '/$shareId',
    path: '/$shareId',
    getParentRoute: () => ApiExamPreviewSharesRoute,
  } as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInitRoute = ApiAdminInitRouteImport.update({
  id: '/api/admin/init',
  path: '/api/admin/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountResolveRoute = ApiAccountResolveRouteImport.update({
  id: '/api/account/resolve',
  path: '/api/account/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorPaperIdRoute = AdminEditorPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => AdminEditorRoute,
} as any)
const ApiPapersPaperIdThresholdsRoute =
  ApiPapersPaperIdThresholdsRouteImport.update({
    id: '/thresholds',
    path: '/thresholds',
    getParentRoute: () => ApiPapersPaperIdRoute,
  } as any)
const ApiPapersPaperIdQuestionsRoute =
  ApiPapersPaperIdQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => ApiPapersPaperIdRoute,
  } as any)
const ApiPapersPaperIdAnswerKeyRoute =
  ApiPapersPaperIdAnswerKeyRouteImport.update({
    id: '/answer-key',
    path: '/answer-key',
    getParentRoute: () => ApiPapersPaperIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/smart-solve-all': typeof SmartSolveAllRoute
  '/smart-solve-bio': typeof SmartSolveBioRoute
  '/smart-solve-chem': typeof SmartSolveChemRoute
  '/smart-solve-papers': typeof SmartSolvePapersRoute
  '/smart-solve-phys': typeof SmartSolvePhysRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/editor': typeof AdminEditorRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/daily-challenge': typeof ApiDailyChallengeRoute
  '/api/daily-goals': typeof ApiDailyGoalsRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/exam-preview-shares': typeof ApiExamPreviewSharesRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/feedback-notes': typeof ApiFeedbackNotesRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/papers': typeof ApiPapersRouteWithChildren
  '/api/papers-overrides': typeof ApiPapersOverridesRoute
  '/api/planner-tasks': typeof ApiPlannerTasksRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/volunteer-applications': typeof ApiVolunteerApplicationsRoute
  '/api/wallet': typeof ApiWalletRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/desk': typeof DashboardDeskRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smart-solve-all/exam-preview': typeof SmartSolveAllExamPreviewRoute
  '/smart-solve-bio/exam-preview': typeof SmartSolveBioExamPreviewRoute
  '/smart-solve-chem/exam-preview': typeof SmartSolveChemExamPreviewRoute
  '/smart-solve-papers/$paperId': typeof SmartSolvePapersPaperIdRoute
  '/smart-solve-phys/exam-preview': typeof SmartSolvePhysExamPreviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/editor/$paperId': typeof AdminEditorPaperIdRoute
  '/api/account/resolve': typeof ApiAccountResolveRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/exam-preview-shares/$shareId': typeof ApiExamPreviewSharesShareIdRoute
  '/api/feedback-notes/$id': typeof ApiFeedbackNotesIdRoute
  '/api/papers/$paperId': typeof ApiPapersPaperIdRouteWithChildren
  '/api/planner-tasks/$id': typeof ApiPlannerTasksIdRoute
  '/api/public-profile/$username': typeof ApiPublicProfileUsernameRoute
  '/dashboard/tables/$subject': typeof DashboardTablesSubjectRoute
  '/api/papers/$paperId/answer-key': typeof ApiPapersPaperIdAnswerKeyRoute
  '/api/papers/$paperId/questions': typeof ApiPapersPaperIdQuestionsRoute
  '/api/papers/$paperId/thresholds': typeof ApiPapersPaperIdThresholdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/smart-solve-all': typeof SmartSolveAllRoute
  '/smart-solve-bio': typeof SmartSolveBioRoute
  '/smart-solve-chem': typeof SmartSolveChemRoute
  '/smart-solve-papers': typeof SmartSolvePapersRoute
  '/smart-solve-phys': typeof SmartSolvePhysRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/editor': typeof AdminEditorRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/daily-challenge': typeof ApiDailyChallengeRoute
  '/api/daily-goals': typeof ApiDailyGoalsRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/exam-preview-shares': typeof ApiExamPreviewSharesRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/feedback-notes': typeof ApiFeedbackNotesRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/papers': typeof ApiPapersRouteWithChildren
  '/api/papers-overrides': typeof ApiPapersOverridesRoute
  '/api/planner-tasks': typeof ApiPlannerTasksRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/volunteer-applications': typeof ApiVolunteerApplicationsRoute
  '/api/wallet': typeof ApiWalletRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/desk': typeof DashboardDeskRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smart-solve-all/exam-preview': typeof SmartSolveAllExamPreviewRoute
  '/smart-solve-bio/exam-preview': typeof SmartSolveBioExamPreviewRoute
  '/smart-solve-chem/exam-preview': typeof SmartSolveChemExamPreviewRoute
  '/smart-solve-papers/$paperId': typeof SmartSolvePapersPaperIdRoute
  '/smart-solve-phys/exam-preview': typeof SmartSolvePhysExamPreviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/editor/$paperId': typeof AdminEditorPaperIdRoute
  '/api/account/resolve': typeof ApiAccountResolveRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/exam-preview-shares/$shareId': typeof ApiExamPreviewSharesShareIdRoute
  '/api/feedback-notes/$id': typeof ApiFeedbackNotesIdRoute
  '/api/papers/$paperId': typeof ApiPapersPaperIdRouteWithChildren
  '/api/planner-tasks/$id': typeof ApiPlannerTasksIdRoute
  '/api/public-profile/$username': typeof ApiPublicProfileUsernameRoute
  '/dashboard/tables/$subject': typeof DashboardTablesSubjectRoute
  '/api/papers/$paperId/answer-key': typeof ApiPapersPaperIdAnswerKeyRoute
  '/api/papers/$paperId/questions': typeof ApiPapersPaperIdQuestionsRoute
  '/api/papers/$paperId/thresholds': typeof ApiPapersPaperIdThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/smart-solve-all': typeof SmartSolveAllRoute
  '/smart-solve-bio': typeof SmartSolveBioRoute
  '/smart-solve-chem': typeof SmartSolveChemRoute
  '/smart-solve-papers': typeof SmartSolvePapersRoute
  '/smart-solve-phys': typeof SmartSolvePhysRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/editor': typeof AdminEditorRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/daily-challenge': typeof ApiDailyChallengeRoute
  '/api/daily-goals': typeof ApiDailyGoalsRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/exam-preview-shares': typeof ApiExamPreviewSharesRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/feedback-notes': typeof ApiFeedbackNotesRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/papers': typeof ApiPapersRouteWithChildren
  '/api/papers-overrides': typeof ApiPapersOverridesRoute
  '/api/planner-tasks': typeof ApiPlannerTasksRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/volunteer-applications': typeof ApiVolunteerApplicationsRoute
  '/api/wallet': typeof ApiWalletRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/desk': typeof DashboardDeskRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/smart-solve-all_/exam-preview': typeof SmartSolveAllExamPreviewRoute
  '/smart-solve-bio_/exam-preview': typeof SmartSolveBioExamPreviewRoute
  '/smart-solve-chem_/exam-preview': typeof SmartSolveChemExamPreviewRoute
  '/smart-solve-papers_/$paperId': typeof SmartSolvePapersPaperIdRoute
  '/smart-solve-phys_/exam-preview': typeof SmartSolvePhysExamPreviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/editor/$paperId': typeof AdminEditorPaperIdRoute
  '/api/account/resolve': typeof ApiAccountResolveRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/exam-preview-shares/$shareId': typeof ApiExamPreviewSharesShareIdRoute
  '/api/feedback-notes/$id': typeof ApiFeedbackNotesIdRoute
  '/api/papers/$paperId': typeof ApiPapersPaperIdRouteWithChildren
  '/api/planner-tasks/$id': typeof ApiPlannerTasksIdRoute
  '/api/public-profile/$username': typeof ApiPublicProfileUsernameRoute
  '/dashboard/tables/$subject': typeof DashboardTablesSubjectRoute
  '/api/papers/$paperId/answer-key': typeof ApiPapersPaperIdAnswerKeyRoute
  '/api/papers/$paperId/questions': typeof ApiPapersPaperIdQuestionsRoute
  '/api/papers/$paperId/thresholds': typeof ApiPapersPaperIdThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/leaderboard'
    | '/planner'
    | '/profile'
    | '/search'
    | '/smart-solve-all'
    | '/smart-solve-bio'
    | '/smart-solve-chem'
    | '/smart-solve-papers'
    | '/smart-solve-phys'
    | '/volunteer'
    | '/admin/editor'
    | '/api/analytics'
    | '/api/daily-challenge'
    | '/api/daily-goals'
    | '/api/desk'
    | '/api/exam-preview-shares'
    | '/api/feedback'
    | '/api/feedback-notes'
    | '/api/leaderboard'
    | '/api/papers'
    | '/api/papers-overrides'
    | '/api/planner-tasks'
    | '/api/profile'
    | '/api/send-email'
    | '/api/streaks'
    | '/api/volunteer-applications'
    | '/api/wallet'
    | '/dashboard/analytics'
    | '/dashboard/desk'
    | '/profile/$username'
    | '/smart-solve-all/exam-preview'
    | '/smart-solve-bio/exam-preview'
    | '/smart-solve-chem/exam-preview'
    | '/smart-solve-papers/$paperId'
    | '/smart-solve-phys/exam-preview'
    | '/dashboard/'
    | '/admin/editor/$paperId'
    | '/api/account/resolve'
    | '/api/admin/bootstrap'
    | '/api/admin/init'
    | '/api/admin/seed'
    | '/api/exam-preview-shares/$shareId'
    | '/api/feedback-notes/$id'
    | '/api/papers/$paperId'
    | '/api/planner-tasks/$id'
    | '/api/public-profile/$username'
    | '/dashboard/tables/$subject'
    | '/api/papers/$paperId/answer-key'
    | '/api/papers/$paperId/questions'
    | '/api/papers/$paperId/thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/feedback'
    | '/help'
    | '/leaderboard'
    | '/planner'
    | '/profile'
    | '/search'
    | '/smart-solve-all'
    | '/smart-solve-bio'
    | '/smart-solve-chem'
    | '/smart-solve-papers'
    | '/smart-solve-phys'
    | '/volunteer'
    | '/admin/editor'
    | '/api/analytics'
    | '/api/daily-challenge'
    | '/api/daily-goals'
    | '/api/desk'
    | '/api/exam-preview-shares'
    | '/api/feedback'
    | '/api/feedback-notes'
    | '/api/leaderboard'
    | '/api/papers'
    | '/api/papers-overrides'
    | '/api/planner-tasks'
    | '/api/profile'
    | '/api/send-email'
    | '/api/streaks'
    | '/api/volunteer-applications'
    | '/api/wallet'
    | '/dashboard/analytics'
    | '/dashboard/desk'
    | '/profile/$username'
    | '/smart-solve-all/exam-preview'
    | '/smart-solve-bio/exam-preview'
    | '/smart-solve-chem/exam-preview'
    | '/smart-solve-papers/$paperId'
    | '/smart-solve-phys/exam-preview'
    | '/dashboard'
    | '/admin/editor/$paperId'
    | '/api/account/resolve'
    | '/api/admin/bootstrap'
    | '/api/admin/init'
    | '/api/admin/seed'
    | '/api/exam-preview-shares/$shareId'
    | '/api/feedback-notes/$id'
    | '/api/papers/$paperId'
    | '/api/planner-tasks/$id'
    | '/api/public-profile/$username'
    | '/dashboard/tables/$subject'
    | '/api/papers/$paperId/answer-key'
    | '/api/papers/$paperId/questions'
    | '/api/papers/$paperId/thresholds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/leaderboard'
    | '/planner'
    | '/profile'
    | '/search'
    | '/smart-solve-all'
    | '/smart-solve-bio'
    | '/smart-solve-chem'
    | '/smart-solve-papers'
    | '/smart-solve-phys'
    | '/volunteer'
    | '/admin/editor'
    | '/api/analytics'
    | '/api/daily-challenge'
    | '/api/daily-goals'
    | '/api/desk'
    | '/api/exam-preview-shares'
    | '/api/feedback'
    | '/api/feedback-notes'
    | '/api/leaderboard'
    | '/api/papers'
    | '/api/papers-overrides'
    | '/api/planner-tasks'
    | '/api/profile'
    | '/api/send-email'
    | '/api/streaks'
    | '/api/volunteer-applications'
    | '/api/wallet'
    | '/dashboard/analytics'
    | '/dashboard/desk'
    | '/profile/$username'
    | '/smart-solve-all_/exam-preview'
    | '/smart-solve-bio_/exam-preview'
    | '/smart-solve-chem_/exam-preview'
    | '/smart-solve-papers_/$paperId'
    | '/smart-solve-phys_/exam-preview'
    | '/dashboard/'
    | '/admin/editor/$paperId'
    | '/api/account/resolve'
    | '/api/admin/bootstrap'
    | '/api/admin/init'
    | '/api/admin/seed'
    | '/api/exam-preview-shares/$shareId'
    | '/api/feedback-notes/$id'
    | '/api/papers/$paperId'
    | '/api/planner-tasks/$id'
    | '/api/public-profile/$username'
    | '/dashboard/tables/$subject'
    | '/api/papers/$paperId/answer-key'
    | '/api/papers/$paperId/questions'
    | '/api/papers/$paperId/thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SearchRoute: typeof SearchRoute
  SmartSolveAllRoute: typeof SmartSolveAllRoute
  SmartSolveBioRoute: typeof SmartSolveBioRoute
  SmartSolveChemRoute: typeof SmartSolveChemRoute
  SmartSolvePapersRoute: typeof SmartSolvePapersRoute
  SmartSolvePhysRoute: typeof SmartSolvePhysRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiDailyChallengeRoute: typeof ApiDailyChallengeRoute
  ApiDailyGoalsRoute: typeof ApiDailyGoalsRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiExamPreviewSharesRoute: typeof ApiExamPreviewSharesRouteWithChildren
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiFeedbackNotesRoute: typeof ApiFeedbackNotesRouteWithChildren
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiPapersRoute: typeof ApiPapersRouteWithChildren
  ApiPapersOverridesRoute: typeof ApiPapersOverridesRoute
  ApiPlannerTasksRoute: typeof ApiPlannerTasksRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiStreaksRoute: typeof ApiStreaksRoute
  ApiVolunteerApplicationsRoute: typeof ApiVolunteerApplicationsRoute
  ApiWalletRoute: typeof ApiWalletRoute
  SmartSolveAllExamPreviewRoute: typeof SmartSolveAllExamPreviewRoute
  SmartSolveBioExamPreviewRoute: typeof SmartSolveBioExamPreviewRoute
  SmartSolveChemExamPreviewRoute: typeof SmartSolveChemExamPreviewRoute
  SmartSolvePapersPaperIdRoute: typeof SmartSolvePapersPaperIdRoute
  SmartSolvePhysExamPreviewRoute: typeof SmartSolvePhysExamPreviewRoute
  ApiAccountResolveRoute: typeof ApiAccountResolveRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminInitRoute: typeof ApiAdminInitRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiPublicProfileUsernameRoute: typeof ApiPublicProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-phys': {
      id: '/smart-solve-phys'
      path: '/smart-solve-phys'
      fullPath: '/smart-solve-phys'
      preLoaderRoute: typeof SmartSolvePhysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-papers': {
      id: '/smart-solve-papers'
      path: '/smart-solve-papers'
      fullPath: '/smart-solve-papers'
      preLoaderRoute: typeof SmartSolvePapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-chem': {
      id: '/smart-solve-chem'
      path: '/smart-solve-chem'
      fullPath: '/smart-solve-chem'
      preLoaderRoute: typeof SmartSolveChemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-bio': {
      id: '/smart-solve-bio'
      path: '/smart-solve-bio'
      fullPath: '/smart-solve-bio'
      preLoaderRoute: typeof SmartSolveBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-all': {
      id: '/smart-solve-all'
      path: '/smart-solve-all'
      fullPath: '/smart-solve-all'
      preLoaderRoute: typeof SmartSolveAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/smart-solve-phys_/exam-preview': {
      id: '/smart-solve-phys_/exam-preview'
      path: '/smart-solve-phys/exam-preview'
      fullPath: '/smart-solve-phys/exam-preview'
      preLoaderRoute: typeof SmartSolvePhysExamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-papers_/$paperId': {
      id: '/smart-solve-papers_/$paperId'
      path: '/smart-solve-papers/$paperId'
      fullPath: '/smart-solve-papers/$paperId'
      preLoaderRoute: typeof SmartSolvePapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-chem_/exam-preview': {
      id: '/smart-solve-chem_/exam-preview'
      path: '/smart-solve-chem/exam-preview'
      fullPath: '/smart-solve-chem/exam-preview'
      preLoaderRoute: typeof SmartSolveChemExamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-bio_/exam-preview': {
      id: '/smart-solve-bio_/exam-preview'
      path: '/smart-solve-bio/exam-preview'
      fullPath: '/smart-solve-bio/exam-preview'
      preLoaderRoute: typeof SmartSolveBioExamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-solve-all_/exam-preview': {
      id: '/smart-solve-all_/exam-preview'
      path: '/smart-solve-all/exam-preview'
      fullPath: '/smart-solve-all/exam-preview'
      preLoaderRoute: typeof SmartSolveAllExamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dashboard/desk': {
      id: '/dashboard/desk'
      path: '/desk'
      fullPath: '/dashboard/desk'
      preLoaderRoute: typeof DashboardDeskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/wallet': {
      id: '/api/wallet'
      path: '/api/wallet'
      fullPath: '/api/wallet'
      preLoaderRoute: typeof ApiWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/volunteer-applications': {
      id: '/api/volunteer-applications'
      path: '/api/volunteer-applications'
      fullPath: '/api/volunteer-applications'
      preLoaderRoute: typeof ApiVolunteerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streaks': {
      id: '/api/streaks'
      path: '/api/streaks'
      fullPath: '/api/streaks'
      preLoaderRoute: typeof ApiStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planner-tasks': {
      id: '/api/planner-tasks'
      path: '/api/planner-tasks'
      fullPath: '/api/planner-tasks'
      preLoaderRoute: typeof ApiPlannerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/papers-overrides': {
      id: '/api/papers-overrides'
      path: '/api/papers-overrides'
      fullPath: '/api/papers-overrides'
      preLoaderRoute: typeof ApiPapersOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/papers': {
      id: '/api/papers'
      path: '/api/papers'
      fullPath: '/api/papers'
      preLoaderRoute: typeof ApiPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback-notes': {
      id: '/api/feedback-notes'
      path: '/api/feedback-notes'
      fullPath: '/api/feedback-notes'
      preLoaderRoute: typeof ApiFeedbackNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam-preview-shares': {
      id: '/api/exam-preview-shares'
      path: '/api/exam-preview-shares'
      fullPath: '/api/exam-preview-shares'
      preLoaderRoute: typeof ApiExamPreviewSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-goals': {
      id: '/api/daily-goals'
      path: '/api/daily-goals'
      fullPath: '/api/daily-goals'
      preLoaderRoute: typeof ApiDailyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-challenge': {
      id: '/api/daily-challenge'
      path: '/api/daily-challenge'
      fullPath: '/api/daily-challenge'
      preLoaderRoute: typeof ApiDailyChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/tables/$subject': {
      id: '/dashboard/tables/$subject'
      path: '/tables/$subject'
      fullPath: '/dashboard/tables/$subject'
      preLoaderRoute: typeof DashboardTablesSubjectRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public-profile/$username': {
      id: '/api/public-profile/$username'
      path: '/api/public-profile/$username'
      fullPath: '/api/public-profile/$username'
      preLoaderRoute: typeof ApiPublicProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planner-tasks/$id': {
      id: '/api/planner-tasks/$id'
      path: '/$id'
      fullPath: '/api/planner-tasks/$id'
      preLoaderRoute: typeof ApiPlannerTasksIdRouteImport
      parentRoute: typeof ApiPlannerTasksRoute
    }
    '/api/papers/$paperId': {
      id: '/api/papers/$paperId'
      path: '/$paperId'
      fullPath: '/api/papers/$paperId'
      preLoaderRoute: typeof ApiPapersPaperIdRouteImport
      parentRoute: typeof ApiPapersRoute
    }
    '/api/feedback-notes/$id': {
      id: '/api/feedback-notes/$id'
      path: '/$id'
      fullPath: '/api/feedback-notes/$id'
      preLoaderRoute: typeof ApiFeedbackNotesIdRouteImport
      parentRoute: typeof ApiFeedbackNotesRoute
    }
    '/api/exam-preview-shares/$shareId': {
      id: '/api/exam-preview-shares/$shareId'
      path: '/$shareId'
      fullPath: '/api/exam-preview-shares/$shareId'
      preLoaderRoute: typeof ApiExamPreviewSharesShareIdRouteImport
      parentRoute: typeof ApiExamPreviewSharesRoute
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/init': {
      id: '/api/admin/init'
      path: '/api/admin/init'
      fullPath: '/api/admin/init'
      preLoaderRoute: typeof ApiAdminInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/resolve': {
      id: '/api/account/resolve'
      path: '/api/account/resolve'
      fullPath: '/api/account/resolve'
      preLoaderRoute: typeof ApiAccountResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/$paperId': {
      id: '/admin/editor/$paperId'
      path: '/$paperId'
      fullPath: '/admin/editor/$paperId'
      preLoaderRoute: typeof AdminEditorPaperIdRouteImport
      parentRoute: typeof AdminEditorRoute
    }
    '/api/papers/$paperId/thresholds': {
      id: '/api/papers/$paperId/thresholds'
      path: '/thresholds'
      fullPath: '/api/papers/$paperId/thresholds'
      preLoaderRoute: typeof ApiPapersPaperIdThresholdsRouteImport
      parentRoute: typeof ApiPapersPaperIdRoute
    }
    '/api/papers/$paperId/questions': {
      id: '/api/papers/$paperId/questions'
      path: '/questions'
      fullPath: '/api/papers/$paperId/questions'
      preLoaderRoute: typeof ApiPapersPaperIdQuestionsRouteImport
      parentRoute: typeof ApiPapersPaperIdRoute
    }
    '/api/papers/$paperId/answer-key': {
      id: '/api/papers/$paperId/answer-key'
      path: '/answer-key'
      fullPath: '/api/papers/$paperId/answer-key'
      preLoaderRoute: typeof ApiPapersPaperIdAnswerKeyRouteImport
      parentRoute: typeof ApiPapersPaperIdRoute
    }
  }
}

interface AdminEditorRouteChildren {
  AdminEditorPaperIdRoute: typeof AdminEditorPaperIdRoute
}

const AdminEditorRouteChildren: AdminEditorRouteChildren = {
  AdminEditorPaperIdRoute: AdminEditorPaperIdRoute,
}

const AdminEditorRouteWithChildren = AdminEditorRoute._addFileChildren(
  AdminEditorRouteChildren,
)

interface AdminRouteChildren {
  AdminEditorRoute: typeof AdminEditorRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEditorRoute: AdminEditorRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDeskRoute: typeof DashboardDeskRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTablesSubjectRoute: typeof DashboardTablesSubjectRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDeskRoute: DashboardDeskRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTablesSubjectRoute: DashboardTablesSubjectRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUsernameRoute: ProfileUsernameRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ApiExamPreviewSharesRouteChildren {
  ApiExamPreviewSharesShareIdRoute: typeof ApiExamPreviewSharesShareIdRoute
}

const ApiExamPreviewSharesRouteChildren: ApiExamPreviewSharesRouteChildren = {
  ApiExamPreviewSharesShareIdRoute: ApiExamPreviewSharesShareIdRoute,
}

const ApiExamPreviewSharesRouteWithChildren =
  ApiExamPreviewSharesRoute._addFileChildren(ApiExamPreviewSharesRouteChildren)

interface ApiFeedbackNotesRouteChildren {
  ApiFeedbackNotesIdRoute: typeof ApiFeedbackNotesIdRoute
}

const ApiFeedbackNotesRouteChildren: ApiFeedbackNotesRouteChildren = {
  ApiFeedbackNotesIdRoute: ApiFeedbackNotesIdRoute,
}

const ApiFeedbackNotesRouteWithChildren =
  ApiFeedbackNotesRoute._addFileChildren(ApiFeedbackNotesRouteChildren)

interface ApiPapersPaperIdRouteChildren {
  ApiPapersPaperIdAnswerKeyRoute: typeof ApiPapersPaperIdAnswerKeyRoute
  ApiPapersPaperIdQuestionsRoute: typeof ApiPapersPaperIdQuestionsRoute
  ApiPapersPaperIdThresholdsRoute: typeof ApiPapersPaperIdThresholdsRoute
}

const ApiPapersPaperIdRouteChildren: ApiPapersPaperIdRouteChildren = {
  ApiPapersPaperIdAnswerKeyRoute: ApiPapersPaperIdAnswerKeyRoute,
  ApiPapersPaperIdQuestionsRoute: ApiPapersPaperIdQuestionsRoute,
  ApiPapersPaperIdThresholdsRoute: ApiPapersPaperIdThresholdsRoute,
}

const ApiPapersPaperIdRouteWithChildren =
  ApiPapersPaperIdRoute._addFileChildren(ApiPapersPaperIdRouteChildren)

interface ApiPapersRouteChildren {
  ApiPapersPaperIdRoute: typeof ApiPapersPaperIdRouteWithChildren
}

const ApiPapersRouteChildren: ApiPapersRouteChildren = {
  ApiPapersPaperIdRoute: ApiPapersPaperIdRouteWithChildren,
}

const ApiPapersRouteWithChildren = ApiPapersRoute._addFileChildren(
  ApiPapersRouteChildren,
)

interface ApiPlannerTasksRouteChildren {
  ApiPlannerTasksIdRoute: typeof ApiPlannerTasksIdRoute
}

const ApiPlannerTasksRouteChildren: ApiPlannerTasksRouteChildren = {
  ApiPlannerTasksIdRoute: ApiPlannerTasksIdRoute,
}

const ApiPlannerTasksRouteWithChildren = ApiPlannerTasksRoute._addFileChildren(
  ApiPlannerTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SearchRoute: SearchRoute,
  SmartSolveAllRoute: SmartSolveAllRoute,
  SmartSolveBioRoute: SmartSolveBioRoute,
  SmartSolveChemRoute: SmartSolveChemRoute,
  SmartSolvePapersRoute: SmartSolvePapersRoute,
  SmartSolvePhysRoute: SmartSolvePhysRoute,
  VolunteerRoute: VolunteerRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiDailyChallengeRoute: ApiDailyChallengeRoute,
  ApiDailyGoalsRoute: ApiDailyGoalsRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiExamPreviewSharesRoute: ApiExamPreviewSharesRouteWithChildren,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiFeedbackNotesRoute: ApiFeedbackNotesRouteWithChildren,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiPapersRoute: ApiPapersRouteWithChildren,
  ApiPapersOverridesRoute: ApiPapersOverridesRoute,
  ApiPlannerTasksRoute: ApiPlannerTasksRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiStreaksRoute: ApiStreaksRoute,
  ApiVolunteerApplicationsRoute: ApiVolunteerApplicationsRoute,
  ApiWalletRoute: ApiWalletRoute,
  SmartSolveAllExamPreviewRoute: SmartSolveAllExamPreviewRoute,
  SmartSolveBioExamPreviewRoute: SmartSolveBioExamPreviewRoute,
  SmartSolveChemExamPreviewRoute: SmartSolveChemExamPreviewRoute,
  SmartSolvePapersPaperIdRoute: SmartSolvePapersPaperIdRoute,
  SmartSolvePhysExamPreviewRoute: SmartSolvePhysExamPreviewRoute,
  ApiAccountResolveRoute: ApiAccountResolveRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminInitRoute: ApiAdminInitRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiPublicProfileUsernameRoute: ApiPublicProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
