// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const memoryStore = new Map<string, string>();
const ssrSafeStorage =
  typeof window !== "undefined" && typeof window.localStorage !== "undefined"
    ? window.localStorage
    : {
        getItem: (k: string) => memoryStore.get(k) ?? null,
        setItem: (k: string, v: string) => {
          memoryStore.set(k, v);
        },
        removeItem: (k: string) => {
          memoryStore.delete(k);
        },
      };

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: ssrSafeStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  },
});
